src/js/background.js
Fixes the issue of not opening all the questions
Removes the ID's of the questions in the Array correctly
=> Fixes issues when opening new tabs

src/_locales/en/messages.json, src/_locales/pt-BR/messages.json, src/js/background.js
Fixes issue duplicated question
Updated Strings
=> Fixes issue duplicated question

README.md, src/css/popup.css, src/html/popup.html, src/js/background.js
Security fixes
Updated README.md
Updated loading appearence
Updated Strings
=> Security fixes

src/css/popup.css, src/js/background.js
I assume you hid the scrollbars because they would break the layout. So I fixed this by also adding some containers and using flex to layout everything.
=> Fixed bug #17

src/css/popup.css, src/html/popup.html, src/js/background.js
This may need to be tested a bit more to make sure that there are no bugs, but this is my implementation of the Storage API for bug #19.
I also make the questions that the user has opened appear faded, which could potentially nullify the need for bug #15 unless you want to actually hide the item from the list. However, I no longer feel that's necessary if we distinguish the viewed questions from the old questions.
Also swapped the full screen loading wheel with a top loading bar. The loading wheel is not needed if the questions are first loaded from the Storage API and then updated.
=> Implementation of Storage API

src/css/popup.css, src/html/popup.html
Menu pinned on top
Scrollbar bellow the menu
=> Changes on interface

src/js/background.js
The notification counter now only includes unread questions. Questions that have been viewed are no longer counted. The "clear notification button" now marks all questions as read. This solves issue #14.
=> Patched #14

src/_locales/en/messages.json, src/_locales/pt-BR/messages.json, src/css/bootstrap.css, src/css/style.css, src/html/preferences.html, src/js/background.js, src/js/preferences.js, src/manifest.json
Added Preferences page
Added option to set language and to set time to seek for new questions
( This solves the issue #28 )
=> UI Preferences

src/_locales/pt-BR/messages.json
=> Localization pt-BR

src/js/background.js, src/js/language.js, src/js/preferences.js
Fixes notifications issue after first status change at preferences page being always active
and minor changes.
=> Fixes issue with notifications

src/manifest.json
=> Updated to version 1.0.4

src/_locales/en/messages.json, src/_locales/pt-BR/messages.json, src/html/preferences.html, src/js/background.js, src/js/popup.js, src/js/preferences.js
Added a option in the preferences page to select which product to search for new questions, products:
- Firefox for Desktop
- Firefox for Mobile (Firefox for Android and Firefox for iOS)
- Thunderbird
PR related with the issue #41
=> Option to choose a product

src/html/preferences.html, src/js/preferences.js
Temporary solution to issue #60
=> Search questions in French

src/html/preferences.html, src/js/preferences.js
Questions in French are made in a different forum. This PR fixes issue #60 by removing the option to select French, since we can't track the new opened questions.
=> Removes the option to select French

src/_locales/cs/messages.json, src/_locales/es/messages.json, src/_locales/hu/messages.json, src/html/preferences.html
Added the languages with more questions at support forum (Čeština, Español and Magyar).
=> Add some languages to select search

src/_locales/cs/messages.json, src/_locales/en/messages.json, src/_locales/es/messages.json, src/_locales/fr/messages.json, src/_locales/hu/messages.json, src/_locales/pt-BR/messages.json
Fixes the issue #68 by removing unused strings.
=> Review of unused strings

src/css/popup.css
=> Fixes issue #23

src/html/preferences.html, src/js/background.js, src/js/popup.js, src/js/preferences.js
I added the ability to display and monitor multiple products in the add-on (see issue #48). When more are found, they should be added in the correct order via the ID that each question is assigned.
I think I have worked out all of the bugs, but you may want to test it for a few days before pushing it to the release on AMO.
**NOTE: ** The localization for the preferences page may need to be updated to reflect this change.
=> Added ability to search multiple products

src/css/style.css, src/html/preferences.html, src/js/background.js
Fixes title issue when use the button "Clear notifications" showing now the name of the Add-on
Changes in preferences page interface
Time to consult new issues modified for pre-defined options (15.. 30.. 45.. 60)
=> Fixes some issues including "Clear notifications"

src/js/background.js
I have fixed issue #82 and I will provide a more technical explanation of the cause of the problem and how it was fixed in the issue thread. It's only been tested using JSON responses on my custom server, but it should hold up at release.
I also fixed a minor styling error and a potential problem with the fixed loop size for looping through the list of questions. It would crash if the response only had less than 20 questions listed. I don't believe that this would ever happen, but fixed in just in case.
=> Fixed problem with multiple requests

src/js/background.js, src/js/popup.js
Fixed issue #89 by adding an API call counter to detect the final API call.
=> Fixed issue 89

src/js/background.js, src/js/popup.js
Fixed issue #91 by adding a message handler for no API calls.
=> Fixed issue #91

src/html/preferences.html
Spanish has been deleted by accident during rebasing #58 with master. Also, it seems like Myanar locales hasn't been translated (even before we merge #58). Should we temporarily remove it and ping the person who added it?
=> fix language preferences regression

src/_locales/cs/messages.json, src/_locales/en/messages.json, src/_locales/es/messages.json, src/_locales/fr/messages.json, src/_locales/hu/messages.json, src/_locales/pt-BR/messages.json, src/html/preferences.html
Localization to pt-BR
More localization strings at Preferences page
=> Adds more localization strings at Preferences page

src/_locales/hu/messages.json
I have translated all the strings.
=> Add Hungarian translation

src/_locales/fr/messages.json
I translated the new strings, and reviewed the strings already 'in French'.
=> Translation and proofreading

README.md, src/html/popup.html, src/manifest.json
Increased version number
updated README.md
=> Update to version 1.3.1

src/_locales/cs/messages.json, src/_locales/en/messages.json, src/_locales/es/messages.json, src/_locales/fr/messages.json, src/_locales/hu/messages.json, src/_locales/pt-BR/messages.json, src/css/app.css, src/css/popup.css, src/html/popup.html, src/html/preferences.html, src/js/background.js, src/js/popup.js, src/js/preferences.js
Added support for Android (see issue #74)
=> Added support for Android

src/css/app.css, src/css/popup.css, src/html/popup.html, src/js/popup.js
This pull request has a number of UI fixes and improvements in it. Most are for mobile, but there are some sidebar issues fixed in there too.
~Once it's merged into the main branch, an update should probably be pushed to AMO to make this version 1.4.1.~ ~Actually, hold off on the AMO update. I'm pretty sure I know what the problem is for issue 133.~ Ok, a release can be pushed to AMO once this is approved and merged. I fixed issue 133.
=> Various UI fixes

src/_locales/es/messages.json
Strings in messages.json localized to Spanish.
=> Update Spanish localization

src/css/app.css, src/html/popup.html, src/js/popup.js
I've added templating, as requested in issue #88. I kind of did what @dannycolin suggested on Discourse, with some changes. It should be tested to make sure that it performs the same as the previous method.
=> Added templating

src/_locales/pl/messages.json
Issue #144
* [ X] Put an X between the brackets on this line if you have done all of the 
following:
(MPL 2.0).
=> Polish localization

src/css/popup.css, src/html/popup.html
Not shows the scroll bar on the menu.
following:
(MPL 2.0).
Not shows the scroll bar on the menu.
=> Hides scroll bar

src/_locales/hu/messages.json
following:
(MPL 2.0).
This commit resolves #139
We don't translate "Firefox for Android", "Firefox for iOS" and "Firefox Preview", because we treat them as brand names.
=> Update Hungarian localization

src/js/background.js
Added a question counter to the sidebar title. Closed #167.
=> Added question counter to sidebarAction

src/js/background.js, src/js/popup.js
I made a lot of simplifications to how the arrays are handled, particularly when it comes to cleaning old questions out of the storage. These changes should also fix #166.
I've tested the code overnight and it appears to be working as expected. I will give it the rest of the day to make sure that there are no bugs and then will merge into the master branch. Would like to do the release to AMO as soon as it's merged so that it fixes that bug.
=> Optimized code

src/css/app.css, src/css/popup.css
This pull request closes #128. To fix the issue, I set the popup to a standard size regardless of the content displayed.
=> Made popup a standard size

src/js/background.js
Added a filter to the incoming questions list to ignore questions that do not match the user's selected products and/or selected locales. Closes #182.
=> Added check to see if incoming questions are valid

src/css/components/checkbox.css, src/css/settings.css, src/html/preferences.html
This pull request adds a blue border around the checkout when the box or label is hovered over. It also changes the mouse cursor to pointer when hovering. This closes #181.
=> Added hover effect to checkbox (#181)

src/js/background.js, src/js/popup.js
I was able to figure out a good way to detect if the sidebar is open or closed using the Runtime API's connection functionality. Closes #116.
=> Added sidebar open detection

src/_locales/cs/messages.json, src/_locales/en/messages.json, src/_locales/es/messages.json, src/_locales/fr/messages.json, src/_locales/hu/messages.json, src/_locales/pl/messages.json, src/_locales/pt-BR/messages.json, src/_locales/sv/messages.json, src/css/app.css, src/html/preferences.html, src/js/preferences.js
=> Added page of credits

src/html/preferences.html
=> Added Italian locale to options

src/_locales/cs/messages.json
fix #123 
following:
(MPL 2.0).
=> Update Czech localization

README.md, src/html/preferences.html
=> Moved credit to options page

src/css/app.css, src/html/preferences.html
following:
(MPL 2.0).
#202 
Implemented the NL option within the preferences.
Introduced the "Nederlands" option in the preferences, aligning with the existing pattern.
None identified.
=> Added the NL option to preferences

README.md, src/manifest.json
following:
(MPL 2.0).
Version update.
Updated the manifest.json to v1.6.0  and add the Nederlands option language in the README.md.
No.
No.
=> Version update to v1.6.0

src/css/app.css, src/css/font.css, src/css/popup.css, src/html/popup.html, src/js/popup.js
following:
(MPL 2.0).
Fix #212 
All linting issues have been fixed. I slightly modified popup.js to avoid messing more in the CSS code that has become hard to refactor already. 
I tested multiple permutations for the settings like enabling multiple products, locales and viewing the list in the sidebar.
=> Fix #212 css linting errors
